### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by n8gray** [ReSwift/GitHubBrowserExample#14]
I'm using Xcode 8.3.3, macOS Sierra 10.12.5, Carthage 0.24.0

I cloned the repo and ran `carthage update --no-build` with success, but building the SwiftFlowGitHubBrowser target fails.

```
Failed to read file or folder at /SAPDevelop/Insights/Experiments/ReSwift/GitHubBrowserExample/Carthage/Checkouts/ReSwiftRouter/Carthage/Build/iOS/ReSwift.framework
```

![screen shot 2017-07-25 at 10 31 32 am](https://user-images.githubusercontent.com/82794/28585222-77f3a2b4-7124-11e7-8c58-0cc7cd3342c8.png)

Any suggestions?

Thanks!

**Comment by alephao** [comment]
I had the same issue, `carthage build --platform iOS` solved it

**Comment by n8gray** [comment]
Thanks.  I also got it to work with this command: `carthage update --no-use-binaries --platform iOS`
