### ISSUE TITLE
"Library not loaded" error when running on device

### ISSUE THREAD

**Issue by zubko** [ReSwift/GitHubBrowserExample#2]
When running on device,
I got an error like this for a bunch of frameworks:
<img width="512" alt="screen shot 2016-03-10 at 12 29 35 pm" src="https://cloud.githubusercontent.com/assets/16039/13667576/b9607ca4-e6bf-11e5-9327-7a0137e3fd27.png">

Solved by adding them to "Embeded Binaries":
<img width="539" alt="screen shot 2016-03-10 at 12 58 50 pm" src="https://cloud.githubusercontent.com/assets/16039/13667604/dfe57bcc-e6bf-11e5-897d-da0337c60613.png">

I can make a PR if this is a way to solve this type of error in Carthage.

**Comment by Ben-G** [comment]
Yes, you are right they should be embedded binaries. Technically there is another bug in Xcode that requires the usage of a script instead, but that's only relevant when submitting to the AppStore. 

Thanks for catching this. Keep forgetting when setting up a new project. 

PR definitely welcome :)

**Comment by Ben-G** [comment]
Closing since @zubko solved this with #3 :tada:
