### ISSUE TITLE
Responsibility of keeping Store

### ISSUE THREAD

**Issue by hiqo-ylapitsky** [ReSwift/GitHubBrowserExample#5]
Hello,

It's interesting to find out, if there are any  recommendations for store life cycle handling? In the https://github.com/ReSwift/GitHubBrowserExample Store was placed in the AppDelegate as global variable (I assume to simplify sample project), but in a real project I think more strict rules are more appropriate.

Thank in advance!

**Comment by Ben-G** [comment]
@ylapitsky Very good question. Generally the store is intended to be a global singleton. It's lifetime should be tied to the lifetime of the entire app.

The store variable could certainly live in a different file but I'm not sure if that would add too much value (though I definitely understand the aversion against storing it in the app delegate).

Probably I'll move it into a separate `Store.swift` file for this example.

Does this answer your question at all? 😄

**Comment by Ben-G** [comment]
Seems this has gone stale. Will close for now. Happy to re-open if something comes up!
